"""
Keyword Optimization Middleware
Use Qwen AI to optimize search terms generated by Agent into keywords more suitable for public opinion database query
"""

from openai import OpenAI
import json
import sys
import os
from typing import List, Dict, Any
from dataclasses import dataclass

# Add project root directory to Python path to import config
sys.path.append(os.path.dirname(os.path.dirname(os.path.dirname(__file__))))
from config import settings
from loguru import logger

# Add utils directory to Python path
current_dir = os.path.dirname(os.path.abspath(__file__))
root_dir = os.path.dirname(os.path.dirname(current_dir))
utils_dir = os.path.join(root_dir, 'utils')
if utils_dir not in sys.path:
    sys.path.append(utils_dir)

from retry_helper import with_graceful_retry, SEARCH_API_RETRY_CONFIG

@dataclass
class KeywordOptimizationResponse:
    """Keyword optimization response"""
    original_query: str
    optimized_keywords: List[str]
    reasoning: str
    success: bool
    error_message: str = ""

class KeywordOptimizer:
    """
    Keyword Optimizer
    Use SiliconFlow's Qwen3 model to optimize Agent-generated search terms into keywords closer to real public opinion
    """
    
    def __init__(self, api_key: str = None, base_url: str = None, model_name: str = None):
        """
        Initialize keyword optimizer
        
        Args:
            api_key: SiliconFlow API key, read from config if not provided
            base_url: Interface base address, default use SiliconFlow address provided in config
        """
        self.api_key = api_key or settings.KEYWORD_OPTIMIZER_API_KEY

        if not self.api_key:
            raise ValueError("SiliconFlow API key not found, please set KEYWORD_OPTIMIZER_API_KEY in config.py")

        self.base_url = base_url or settings.KEYWORD_OPTIMIZER_BASE_URL

        self.client = OpenAI(
            api_key=self.api_key,
            base_url=self.base_url
        )
        self.model = model_name or settings.KEYWORD_OPTIMIZER_MODEL_NAME
    
    def optimize_keywords(self, original_query: str, context: str = "") -> KeywordOptimizationResponse:
        """
        Optimize search keywords
        
        Args:
            original_query: Original search query generated by Agent
            context: Additional context information (such as paragraph title, content description, etc.)
            
        Returns:
            KeywordOptimizationResponse: List of optimized keywords
        """
        logger.info(f"🔍 Keyword Optimization Middleware: Processing query '{original_query}'")
        
        try:
            # Build optimization prompt
            system_prompt = self._build_system_prompt()
            user_prompt = self._build_user_prompt(original_query, context)
            
            # Call Qwen API
            response = self._call_qwen_api(system_prompt, user_prompt)
            
            if response["success"]:
                # Parse response
                content = response["content"]
                try:
                    # Try parsing response in JSON format
                    if content.strip().startswith('{'):
                        parsed = json.loads(content)
                        keywords = parsed.get("keywords", [])
                        reasoning = parsed.get("reasoning", "")
                    else:
                        # If not JSON format, try extracting keywords from text
                        keywords = self._extract_keywords_from_text(content)
                        reasoning = content
                    
                    # Validate keyword quality
                    validated_keywords = self._validate_keywords(keywords)
                    
                    logger.info(
                        f"✅ Optimization success: {len(validated_keywords)} keywords" +
                        ("" if not validated_keywords else "\n" +
                         "\n".join([f"   {i}. '{k}'" for i, k in enumerate(validated_keywords, 1)]))
                    )
                        
                    
                    
                    return KeywordOptimizationResponse(
                        original_query=original_query,
                        optimized_keywords=validated_keywords,
                        reasoning=reasoning,
                        success=True
                    )
                
                except Exception as e:
                    logger.warning(f"Failed to parse API response: {e}, using fallback")
                    fallback_keywords = self._fallback_keyword_extraction(original_query)
                    return KeywordOptimizationResponse(
                        original_query=original_query,
                        optimized_keywords=fallback_keywords,
                        reasoning="API response parsing failed, use fallback keyword extraction",
                        success=True
                    )
            else:
                logger.error(f"❌ API call failed: {response['error']}")
                # Use fallback plan
                fallback_keywords = self._fallback_keyword_extraction(original_query)
                return KeywordOptimizationResponse(
                    original_query=original_query,
                    optimized_keywords=fallback_keywords,
                    reasoning="API call failed, use fallback keyword extraction",
                    success=True,
                    error_message=response['error']
                )
                
        except Exception as e:
            logger.error(f"❌ Keyword optimization failed: {str(e)}")
            # Final fallback plan
            fallback_keywords = self._fallback_keyword_extraction(original_query)
            return KeywordOptimizationResponse(
                original_query=original_query,
                optimized_keywords=fallback_keywords,
                reasoning="System error, use fallback keyword extraction",
                success=False,
                error_message=str(e)
            )
    
    def _build_system_prompt(self) -> str:
        """Build system prompt"""
        return """You are a professional public opinion data mining expert. Your task is to optimize the search query provided by the user into keywords more suitable for searching in social media public opinion databases.

**Core Principles**:
1. **Close to Netizen Language**: Use vocabulary that ordinary netizens would use on social media
2. **Avoid Professional Terminology**: Do not use official terms like "public opinion", "propagation", "tendency", "outlook", etc.
3. **Concise and Specific**: Each keyword must be very concise and clear, easy for database matching
4. **Rich in Emotion**: Include emotional expression words commonly used by netizens
5. **Quantity Control**: Provide a minimum of 10 keywords and a maximum of 20 keywords
6. **Avoid Repetition**: Do not deviate from the topic of the initial query

**Important Reminder**: Each keyword must be an indivisible independent term, strictly forbidding spaces inside the term. For example, use "Lei Jun Class Controversy" instead of the incorrect "Lei Jun Class Controversy".

**Output Format**:
Please return the result in JSON format:
{
    "keywords": ["Keyword1", "Keyword2", "Keyword3"],
    "reasoning": "Reason for choosing these keywords"
}

**Example**:
Input: "Wuhan University public opinion management future outlook development trend"
Output:
{
    "keywords": ["Wuda", "Wuhan University", "School Management", "University", "Education"],
    "reasoning": "Choose 'Wuda' and 'Wuhan University' as core vocabulary, which are the most commonly used names by netizens; 'School Management' is closer to daily expression than 'Public Opinion Management'; avoid using professional terms like 'Future Outlook', 'Development Trend' which are rarely used by netizens"
}"""

    def _build_user_prompt(self, original_query: str, context: str) -> str:
        """Build user prompt"""
        prompt = f"Please optimize the following search query into keywords suitable for public opinion database query:\n\nOriginal query: {original_query}"
        
        if context:
            prompt += f"\n\nContext information: {context}"
        
        prompt += "\n\nPlease remember: Use vocabulary really used by netizens on social media, avoid official terms and professional vocabulary."
        
        return prompt
    
    @with_graceful_retry(SEARCH_API_RETRY_CONFIG, default_return={"success": False, "error": "Keyword optimization service temporarily unavailable"})
    def _call_qwen_api(self, system_prompt: str, user_prompt: str) -> Dict[str, Any]:
        """Call Qwen API"""
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt}
                ],
                temperature=0.7,
            )

            if response.choices:
                content = response.choices[0].message.content
                return {"success": True, "content": content}
            else:
                return {"success": False, "error": "API return format exception"}
        except Exception as e:
            return {"success": False, "error": f"API call exception: {str(e)}"}
    
    def _extract_keywords_from_text(self, text: str) -> List[str]:
        """Extract keywords from text (used when JSON parsing fails)"""
        # Simple keyword extraction logic
        lines = text.split('\n')
        keywords = []
        
        for line in lines:
            line = line.strip()
            # Find possible keywords
            if '：' in line or ':' in line:
                parts = line.split('：') if '：' in line else line.split(':')
                if len(parts) > 1:
                    potential_keywords = parts[1].strip()
                    # Try splitting keywords
                    if '、' in potential_keywords:
                        keywords.extend([k.strip() for k in potential_keywords.split('、')])
                    elif ',' in potential_keywords:
                        keywords.extend([k.strip() for k in potential_keywords.split(',')])
                    else:
                        keywords.append(potential_keywords)
        
        # If not found, try other methods
        if not keywords:
            # Find content in quotes
            import re
            quoted_content = re.findall(r'["""\'](.*?)["""\']', text)
            keywords.extend(quoted_content)
        
        # Clean and validate keywords
        cleaned_keywords = []
        for keyword in keywords[:20]:  # Max 20
            keyword = keyword.strip().strip('"\'""''')
            if keyword and len(keyword) <= 20:  # Reasonable length
                cleaned_keywords.append(keyword)
        
        return cleaned_keywords[:20]
    
    def _validate_keywords(self, keywords: List[str]) -> List[str]:
        """Validate and clean keywords"""
        validated = []
        
        # Bad keywords (too professional or official)
        bad_keywords = {
            '态度分析', '公众反应', '情绪倾向',
            '未来展望', '发展趋势', '战略规划', '政策导向', '管理机制'
        }
        
        for keyword in keywords:
            if isinstance(keyword, str):
                keyword = keyword.strip().strip('"\'""''')
                
                # Basic validation
                if (keyword and 
                    len(keyword) <= 20 and 
                    len(keyword) >= 1 and
                    not any(bad_word in keyword for bad_word in bad_keywords)):
                    validated.append(keyword)
        
        return validated[:20]  # Return max 20 keywords
    
    def _fallback_keyword_extraction(self, original_query: str) -> List[str]:
        """Fallback keyword extraction plan"""
        # Simple keyword extraction logic
        # Remove common useless words
        stop_words = {'、'}
        
        # Split query
        import re
        # Split by spaces, punctuation
        tokens = re.split(r'[\s，。！？；：、]+', original_query)
        
        keywords = []
        for token in tokens:
            token = token.strip()
            if token and token not in stop_words and len(token) >= 2:
                keywords.append(token)
        
        # If no valid keywords, use first word of original query
        if not keywords:
            first_word = original_query.split()[0] if original_query.split() else original_query
            keywords = [first_word] if first_word else ["热门"]
        
        return keywords[:20]

# Global instance
keyword_optimizer = KeywordOptimizer()
